In [1]:
import pandas as pd
import numpy as np

### Load CSV

In [5]:
data_df = pd.read_csv("../02_Data/07_Predictions/z_prediction.csv",index_col=0)
data_df.head()

,code,zoning,coverage,url,prediction,predicted_zoning,move_file_tuple
4052,4052,res_low,0.1071,../02_Data/03_Images/02_PSD_Processed/05_0.25x...,[[0. 0. 0. 0. 0. 0.605 0.397]],res_low,"('004052', 'res_low', 'res_low')"
4053,4053,res_low,0.0890,../02_Data/03_Images/02_PSD_Processed/05_0.25x...,[[0. 0.761 0. 0. 0. 0.233 0. ]],com_med,"('004053', 'res_low', 'com_med')"
5053,5053,res_low,0.2100,../02_Data/03_Images/02_PSD_Processed/05_0.25x...,[[0. 0. 0. 0. 0. 1.001 0. ]],res_low,"('005053', 'res_low', 'res_low')"
6041,6041,res_low,0.1099,../02_Data/03_Images/02_PSD_Processed/05_0.25x...,[[0. 0. 0. 0. 0. 1.005 0. ]],res_low,"('006041', 'res_low', 'res_low')"
6042,6042,res_low,0.0946,../02_Data/03_Images/02_PSD_Processed/05_0.25x...,[[0. 0.205 0.207 0.19 0. 0.387 0. ]],res_low,"('006042', 'res_low', 'res_low')"

### Split Code to Row + Column

In [26]:
def get_grid(row):
    row = str(row)
    column_coord = row[-3:]
    row_coord = row[:-3]
    return row_coord, column_coord

In [27]:
get_grid("4052")

('4', '052')

In [34]:
data_df["row"] = data_df["code"].apply(get_grid)                 # Get Tuple of Row, Column
data_df["column"] = data_df["row"].apply(lambda x: int(x[1]))    # Grab Column from Tuple
data_df["row"] = data_df["row"].apply(lambda x: int(x[0]))       # Grab Row from Tuple
data_df.head()

,code,zoning,coverage,url,prediction,predicted_zoning,move_file_tuple,row,column
4052,4052,res_low,0.1071,../02_Data/03_Images/02_PSD_Processed/05_0.25x...,[[0. 0. 0. 0. 0. 0.605 0.397]],res_low,"('004052', 'res_low', 'res_low')",4,52
4053,4053,res_low,0.0890,../02_Data/03_Images/02_PSD_Processed/05_0.25x...,[[0. 0.761 0. 0. 0. 0.233 0. ]],com_med,"('004053', 'res_low', 'com_med')",4,53
5053,5053,res_low,0.2100,../02_Data/03_Images/02_PSD_Processed/05_0.25x...,[[0. 0. 0. 0. 0. 1.001 0. ]],res_low,"('005053', 'res_low', 'res_low')",5,53
6041,6041,res_low,0.1099,../02_Data/03_Images/02_PSD_Processed/05_0.25x...,[[0. 0. 0. 0. 0. 1.005 0. ]],res_low,"('006041', 'res_low', 'res_low')",6,41
6042,6042,res_low,0.0946,../02_Data/03_Images/02_PSD_Processed/05_0.25x...,[[0. 0.205 0.207 0.19 0. 0.387 0. ]],res_low,"('006042', 'res_low', 'res_low')",6,42

### Find Rows/Columns for GPS Cross-Check
Look for extreme min and max for rows and columns to correspond the GPS coordinates back to the images

In [67]:
data_df[data_df["row"]==28].head()

,code,zoning,coverage,url,prediction,predicted_zoning,move_file_tuple,row,column
28043,28043,res_low,0.1567,../02_Data/03_Images/02_PSD_Processed/05_0.25x...,[[0. 0.601 0. 0. 0.398 0. 0. ]],com_med,"('028043', 'res_low', 'com_med')",28,43
28044,28044,res_low,0.2674,../02_Data/03_Images/02_PSD_Processed/05_0.25x...,[[0. 0. 0. 0.983 0. 0. 0. ]],ind_office_med,"('028044', 'res_low', 'ind_office_med')",28,44
28045,28045,res_low,0.2110,../02_Data/03_Images/02_PSD_Processed/05_0.25x...,[[0. 0. 1.007 0. 0. 0. 0. ]],ind_high,"('028045', 'res_low', 'ind_high')",28,45
28049,28049,res_low,0.0795,../02_Data/03_Images/02_PSD_Processed/05_0.25x...,[[0. 1.011 0. 0. 0. 0. 0. ]],com_med,"('028049', 'res_low', 'com_med')",28,49
28084,28084,res_med,0.3205,../02_Data/03_Images/02_PSD_Processed/05_0.25x...,[[0. 0. 0. 0. 0. 1.003 0. ]],res_low,"('028084', 'res_med', 'res_low')",28,84

### GPS Outputs
Refer to Excel Spreadsheet "GPS" for more detail

Row = Latitude

Column = Longitude

In [71]:
lat_per_image = -0.00181471370967745
long_per_image = 0.00224789423076922

In [72]:
lat_origin = 36.340694733871
long_origin = -115.385946384615

In [73]:
data_df["lat"] = data_df["row"].apply(lambda x: x*lat_per_image + lat_origin + lat_per_image/2)  
data_df["long"] = data_df["column"].apply(lambda x: x*long_per_image + long_origin + long_per_image/2)

# last /2 is for center point of lat & long

In [74]:
data_df.head()

,code,zoning,coverage,url,prediction,predicted_zoning,move_file_tuple,row,column,lat,long
4052,4052,res_low,0.1071,../02_Data/03_Images/02_PSD_Processed/05_0.25x...,[[0. 0. 0. 0. 0. 0.605 0.397]],res_low,"('004052', 'res_low', 'res_low')",4,52,36.332529,-115.267932
4053,4053,res_low,0.0890,../02_Data/03_Images/02_PSD_Processed/05_0.25x...,[[0. 0.761 0. 0. 0. 0.233 0. ]],com_med,"('004053', 'res_low', 'com_med')",4,53,36.332529,-115.265684
5053,5053,res_low,0.2100,../02_Data/03_Images/02_PSD_Processed/05_0.25x...,[[0. 0. 0. 0. 0. 1.001 0. ]],res_low,"('005053', 'res_low', 'res_low')",5,53,36.330714,-115.265684
6041,6041,res_low,0.1099,../02_Data/03_Images/02_PSD_Processed/05_0.25x...,[[0. 0. 0. 0. 0. 1.005 0. ]],res_low,"('006041', 'res_low', 'res_low')",6,41,36.328899,-115.292659
6042,6042,res_low,0.0946,../02_Data/03_Images/02_PSD_Processed/05_0.25x...,[[0. 0.205 0.207 0.19 0. 0.387 0. ]],res_low,"('006042', 'res_low', 'res_low')",6,42,36.328899,-115.290411

### Export to CSV

In [76]:
export_df = data_df[["code","zoning","predicted_zoning","lat","long"]]
export_df.head()

      code   zoning predicted_zoning        lat        long
4052  4052  res_low          res_low  36.332529 -115.267932
4053  4053  res_low          com_med  36.332529 -115.265684
5053  5053  res_low          res_low  36.330714 -115.265684
6041  6041  res_low          res_low  36.328899 -115.292659
6042  6042  res_low          res_low  36.328899 -115.290411

In [77]:
export_df.to_csv("../09_Tableau/gps.csv")